<select class="form-control form-control-sm @error('ville') is-invalid @enderror" name="ville" value="{{ old('ville') }}">
              <option value='Afourar'>Afourar</option>
              <option value='Agadir'>Agadir</option>
              <option value='Agdz'>Agdz</option>
              <option value='Aghbala'>Aghbala</option>
              <option value='Agni Izimmer'>Agni Izimmer</option>
              <option value='Agourai'>Agourai</option>
              <option value='Ahfir'>Ahfir</option>
              <option value='Ain El Aouda'>Ain El Aouda</option>
              <option value='Ain Taoujdate'>Ain Taoujdate</option>
              <option value='Ait Daoud'>Ait Daoud</option>
              <option value='Ajdir‎'>Ajdir‎</option>
              <option value='Akchour'>Akchour</option>
              <option value='Akka'>Akka</option>
              <option value='Aklim'>Aklim</option>
              <option value='Aknoul‎'>Aknoul‎</option>
              <option value='Al Aroui'>Al Aroui</option>
              <option value='Al Hoceïma‎'>Al Hoceïma‎</option>
              <option value='Alnif'>Alnif</option>
              <option value='Amalou Ighriben'>Amalou Ighriben</option>
              <option value='Amizmiz'>Amizmiz</option>
              <option value='Anzi'>Anzi</option>
              <option value='Aoufous'>Aoufous</option>
              <option value='Aoulouz'>Aoulouz</option>
              <option value='Aourir'>Aourir</option>
              <option value='Arazane'>Arazane</option>
              <option value='Arbaoua'>Arbaoua</option>
              <option value='Arfoud'>Arfoud</option>
              <option value='Assa'>Assa</option>
              <option value='Assahrij'>Assahrij</option>
              <option value='Assilah'>Assilah</option>
              <option value='Awsard'>Awsard</option>
              <option value='Azemmour'>Azemmour</option>
              <option value='Azilal'>Azilal</option>
              <option value='Azrou'>Azrou</option>
              <option value='Aïn Bni Mathar'>Aïn Bni Mathar</option>
              <option value='Aïn Cheggag'>Aïn Cheggag</option>
              <option value='Aïn Dorij'>Aïn Dorij</option>
              <option value='Aïn Erreggada'>Aïn Erreggada</option>
              <option value='Aïn Harrouda'>Aïn Harrouda</option>
              <option value='Aïn Jemaa'>Aïn Jemaa</option>
              <option value='Aïn Karma'>Aïn Karma</option>
              <option value='Aïn Leuh'>Aïn Leuh</option>
              <option value='Aït Attab'>Aït Attab</option>
              <option value='Aït Baha'>Aït Baha</option>
              <option value='Aït Boubidmane'>Aït Boubidmane</option>
              <option value='Aït Hichem‎'>Aït Hichem‎</option>
              <option value='Aït Iaâza'>Aït Iaâza</option>
              <option value='Aït Ishaq'>Aït Ishaq</option>
              <option value='Aït Majden'>Aït Majden</option>
              <option value='Aït Melloul'>Aït Melloul</option>
              <option value='Aït Ourir'>Aït Ourir</option>
              <option value='Aït Yalla'>Aït Yalla</option>
              <option value='Bab Berred'>Bab Berred</option>
              <option value='Bab Taza'>Bab Taza</option>
              <option value='Bejaâd'>Bejaâd</option>
              <option value='Ben Ahmed'>Ben Ahmed</option>
              <option value='Ben Guerir'>Ben Guerir</option>
              <option value='Ben Sergao'>Ben Sergao</option>
              <option value='Ben Taïeb'>Ben Taïeb</option>
              <option value='Ben Yakhlef'>Ben Yakhlef</option>
              <option value='Beni Ayat'>Beni Ayat</option>
              <option value='Benslimane'>Benslimane</option>
              <option value='Berkane'>Berkane</option>
              <option value='Berrechid'>Berrechid</option>
              <option value='Bhalil'>Bhalil</option>
              <option value='Bin elouidane'>Bin elouidane</option>
              <option value='Biougra'>Biougra</option>
              <option value='Bir Jdid'>Bir Jdid</option>
              <option value='Bni Ansar'>Bni Ansar</option>
              <option value='Bni Bouayach‎'>Bni Bouayach‎</option>
              <option value='Bni Chiker'>Bni Chiker</option>
              <option value='Bni Drar'>Bni Drar</option>
              <option value='Bni Hadifa‎'>Bni Hadifa‎</option>
              <option value='Bni Tadjite'>Bni Tadjite</option>
              <option value='Bouanane'>Bouanane</option>
              <option value='Bouarfa'>Bouarfa</option>
              <option value='Boudnib'>Boudnib</option>
              <option value='Boufakrane'>Boufakrane</option>
              <option value='Bouguedra'>Bouguedra</option>
              <option value='Bouhdila'>Bouhdila</option>
              <option value='Bouizakarne'>Bouizakarne</option>
              <option value='Boujdour‎'>Boujdour‎</option>
              <option value='Boujniba'>Boujniba</option>
              <option value='Boulanouare'>Boulanouare</option>
              <option value='Boulemane'>Boulemane</option>
              <option value='Boumalne-Dadès'>Boumalne-Dadès</option>
              <option value='Boumia'>Boumia</option>
              <option value='Bouskoura'>Bouskoura</option>
              <option value='Bouznika'>Bouznika</option>
              <option value='Bradia'>Bradia</option>
              <option value='Brikcha'>Brikcha</option>
              <option value='Bzou'>Bzou</option>
              <option value='Béni Mellal'>Béni Mellal</option>
              <option value='Casablanca'>Casablanca</option>
              <option value='Chefchaouen'>Chefchaouen</option>
              <option value='Chichaoua'>Chichaoua</option>
              <option value='Dar Bni Karrich'>Dar Bni Karrich</option>
              <option value='Dar Chaoui'>Dar Chaoui</option>
              <option value='Dar El Kebdani'>Dar El Kebdani</option>
              <option value='Dar Gueddari'>Dar Gueddari</option>
              <option value='Dar Oulad Zidouh'>Dar Oulad Zidouh</option>
              <option value='Dcheira El Jihadia'>Dcheira El Jihadia</option>
              <option value='Debdou'>Debdou</option>
              <option value='Demnate'>Demnate</option>
              <option value='Deroua'>Deroua</option>
              <option value='Douar Kannine'>Douar Kannine</option>
              <option value='Dra'a'>Dra'a</option>
              <option value='Drargua'>Drargua</option>
              <option value='Driouch'>Driouch</option>
              <option value='Echemmaia'>Echemmaia</option>
              <option value='El Aïoun Sidi Mellouk'>El Aïoun Sidi Mellouk</option>
              <option value='El Borouj'>El Borouj</option>
              <option value='El Gara'>El Gara</option>
              <option value='El Guerdane'>El Guerdane</option>
              <option value='El Hajeb'>El Hajeb</option>
              <option value='El Hanchane'>El Hanchane</option>
              <option value='El Jadida'>El Jadida</option>
              <option value='El Kelaâ des Sraghna'>El Kelaâ des Sraghna</option>
              <option value='El Ksiba'>El Ksiba</option>
              <option value='El Marsa‎'>El Marsa‎</option>
              <option value='El Menzel'>El Menzel</option>
              <option value='El Ouatia'>El Ouatia</option>
              <option value='Elkbab'>Elkbab</option>
              <option value='Er-Rich'>Er-Rich</option>
              <option value='Errachidia'>Errachidia</option>
              <option value='Es-Semara'>Es-Semara</option>
              <option value='Essaouira'>Essaouira</option>
              <option value='Fam El Hisn'>Fam El Hisn</option>
              <option value='Farkhana'>Farkhana</option>
              <option value='Figuig'>Figuig</option>
              <option value='Fnideq'>Fnideq</option>
              <option value='Foum Jamaa'>Foum Jamaa</option>
              <option value='Foum Zguid'>Foum Zguid</option>
              <option value='Fquih Ben Salah'>Fquih Ben Salah</option>
              <option value='Fraïta'>Fraïta</option>
              <option value='Fès'>Fès</option>
              <option value='Gardmit'>Gardmit</option>
              <option value='Ghafsai‎'>Ghafsai‎</option>
              <option value='Ghmate'>Ghmate</option>
              <option value='Goulmima'>Goulmima</option>
              <option value='Gourrama'>Gourrama</option>
              <option value='Guelmim'>Guelmim</option>
              <option value='Guercif‎'>Guercif‎</option>
              <option value='Gueznaia'>Gueznaia</option>
              <option value='Guigou'>Guigou</option>
              <option value='Guisser'>Guisser</option>
              <option value='Had Bouhssoussen'>Had Bouhssoussen</option>
              <option value='Had Kourt'>Had Kourt</option>
              <option value='Haj Kaddour'>Haj Kaddour</option>
              <option value='Harhoura'>Harhoura</option>
              <option value='Harte Lyamine'>Harte Lyamine</option>
              <option value='Hattane'>Hattane</option>
              <option value='Hrara'>Hrara</option>
              <option value='Ida Ougnidif'>Ida Ougnidif</option>
              <option value='Ifrane'>Ifrane</option>
              <option value='Ifri'>Ifri</option>
              <option value='Igdamen'>Igdamen</option>
              <option value='Ighil n'Oumgoun'>Ighil n'Oumgoun</option>
              <option value='Ighoud'>Ighoud</option>
              <option value='Ighounane'>Ighounane</option>
              <option value='Ihddaden'>Ihddaden</option>
              <option value='Imassine'>Imassine</option>
              <option value='Imintanoute'>Imintanoute</option>
              <option value='Imouzzer Kandar'>Imouzzer Kandar</option>
              <option value='Imouzzer Marmoucha'>Imouzzer Marmoucha</option>
              <option value='Imzouren‎'>Imzouren‎</option>
              <option value='Inahnahen‎'>Inahnahen‎</option>
              <option value='Inezgane'>Inezgane</option>
              <option value='Irherm'>Irherm</option>
              <option value='Issaguen (Ketama)‎'>Issaguen (Ketama)‎</option>
              <option value='Itzer'>Itzer</option>
              <option value='Jamâat Shaim'>Jamâat Shaim</option>
              <option value='Jaâdar'>Jaâdar</option>
              <option value='Jebha'>Jebha</option>
              <option value='Jerada'>Jerada</option>
              <option value='Jorf'>Jorf</option>
              <option value='Jorf El Melha'>Jorf El Melha</option>
              <option value='Jorf Lasfar'>Jorf Lasfar</option>
              <option value='Karia'>Karia</option>
              <option value='Karia (El Jadida)‎'>Karia (El Jadida)‎</option>
              <option value='Karia Ba Mohamed‎'>Karia Ba Mohamed‎</option>
              <option value='Kariat Arekmane'>Kariat Arekmane</option>
              <option value='Kasba Tadla'>Kasba Tadla</option>
              <option value='Kassita'>Kassita</option>
              <option value='Kattara'>Kattara</option>
              <option value='Kehf Nsour'>Kehf Nsour</option>
              <option value='Kelaat-M'Gouna'>Kelaat-M'Gouna</option>
              <option value='Kerouna'>Kerouna</option>
              <option value='Kerrouchen'>Kerrouchen</option>
              <option value='Khemis Zemamra'>Khemis Zemamra</option>
              <option value='Khenichet'>Khenichet</option>
              <option value='Khouribga'>Khouribga</option>
              <option value='Khémis Sahel'>Khémis Sahel</option>
              <option value='Khémisset'>Khémisset</option>
              <option value='Khénifra'>Khénifra</option>
              <option value='Ksar El Kébir'>Ksar El Kébir</option>
              <option value='Kénitra'>Kénitra</option>
              <option value='Laaounate'>Laaounate</option>
              <option value='Laayoune‎'>Laayoune‎</option>
              <option value='Lakhsas'>Lakhsas</option>
              <option value='Lakhsass'>Lakhsass</option>
              <option value='Lalla Mimouna'>Lalla Mimouna</option>
              <option value='Lalla Takerkoust'>Lalla Takerkoust</option>
              <option value='Larache'>Larache</option>
              <option value='Laâtamna'>Laâtamna</option>
              <option value='Loudaya'>Loudaya</option>
              <option value='Loulad'>Loulad</option>
              <option value='Lqliâa'>Lqliâa</option>
              <option value='Lâattaouia'>Lâattaouia</option>
              <option value='M'diq'>M'diq</option>
              <option value='M'haya'>M'haya</option>
              <option value='M'rirt'>M'rirt</option>
              <option value='M'semrir'>M'semrir</option>
              <option value='Madagh'>Madagh</option>
              <option value='Marrakech'>Marrakech</option>
              <option value='Martil'>Martil</option>
              <option value='Massa (Maroc)'>Massa (Maroc)</option>
              <option value='Mechra Bel Ksiri'>Mechra Bel Ksiri</option>
              <option value='Megousse'>Megousse</option>
              <option value='Mehdia'>Mehdia</option>
              <option value='Meknès‎'>Meknès‎</option>
              <option value='Midar'>Midar</option>
              <option value='Midelt'>Midelt</option>
              <option value='Missour'>Missour</option>
              <option value='Mohammadia'>Mohammadia</option>
              <option value='Moqrisset'>Moqrisset</option>
              <option value='Moulay Abdallah'>Moulay Abdallah</option>
              <option value='Moulay Ali Cherif'>Moulay Ali Cherif</option>
              <option value='Moulay Bouazza'>Moulay Bouazza</option>
              <option value='Moulay Bousselham'>Moulay Bousselham</option>
              <option value='Moulay Brahim'>Moulay Brahim</option>
              <option value='Moulay Idriss Zerhoun'>Moulay Idriss Zerhoun</option>
              <option value='Moulay Yaâcoub'>Moulay Yaâcoub</option>
              <option value='Moussaoua'>Moussaoua</option>
              <option value='MyAliCherif'>MyAliCherif</option>
              <option value='Mzouda'>Mzouda</option>
              <option value='Médiouna'>Médiouna</option>
              <option value='N'Zalat Bni Amar'>N'Zalat Bni Amar</option>
              <option value='Nador'>Nador</option>
              <option value='Naima'>Naima</option>
              <option value='Oualidia'>Oualidia</option>
              <option value='Ouaouizeght'>Ouaouizeght</option>
              <option value='Ouaoumana'>Ouaoumana</option>
              <option value='Ouarzazate'>Ouarzazate</option>
              <option value='Ouazzane'>Ouazzane</option>
              <option value='Oued Amlil‎'>Oued Amlil‎</option>
              <option value='Oued Heimer'>Oued Heimer</option>
              <option value='Oued Ifrane'>Oued Ifrane</option>
              <option value='Oued Laou'>Oued Laou</option>
              <option value='Oued Rmel'>Oued Rmel</option>
              <option value='Oued Zem'>Oued Zem</option>
              <option value='Oued-Eddahab'>Oued-Eddahab</option>
              <option value='Oujda'>Oujda</option>
              <option value='Oulad Abbou'>Oulad Abbou</option>
              <option value='Oulad Amrane'>Oulad Amrane</option>
              <option value='Oulad Ayad'>Oulad Ayad</option>
              <option value='Oulad Berhil'>Oulad Berhil</option>
              <option value='Oulad Frej'>Oulad Frej</option>
              <option value='Oulad Ghadbane'>Oulad Ghadbane</option>
              <option value='Oulad H'Riz Sahel'>Oulad H'Riz Sahel</option>
              <option value='Oulad M'Barek'>Oulad M'Barek</option>
              <option value='Oulad M'rah'>Oulad M'rah</option>
              <option value='Oulad Saïd'>Oulad Saïd</option>
              <option value='Oulad Sidi Ben Daoud'>Oulad Sidi Ben Daoud</option>
              <option value='Oulad Teïma'>Oulad Teïma</option>
              <option value='Oulad Yaich'>Oulad Yaich</option>
              <option value='Oulad Zbair‎'>Oulad Zbair‎</option>
              <option value='Ouled Tayeb'>Ouled Tayeb</option>
              <option value='Oulmès'>Oulmès</option>
              <option value='Ounagha'>Ounagha</option>
              <option value='Outat El Haj'>Outat El Haj</option>
              <option value='Point Cires'>Point Cires</option>
              <option value='Rabat'>Rabat</option>
              <option value='Ras El Aïn'>Ras El Aïn</option>
              <option value='Ras El Ma'>Ras El Ma</option>
              <option value='Ribate El Kheir'>Ribate El Kheir</option>
              <option value='Rissani'>Rissani</option>
              <option value='Rommani'>Rommani</option>
              <option value='Sabaa Aiyoun'>Sabaa Aiyoun</option>
              <option value='Safi'>Safi</option>
              <option value='Salé'>Salé</option>
              <option value='Sarghine'>Sarghine</option>
              <option value='Saïdia'>Saïdia</option>
              <option value='Sebt El Maârif'>Sebt El Maârif</option>
              <option value='Sebt Gzoula'>Sebt Gzoula</option>
              <option value='Sebt Jahjouh'>Sebt Jahjouh</option>
              <option value='Selouane'>Selouane</option>
              <option value='Settat'>Settat</option>
              <option value='Sid L'Mokhtar'>Sid L'Mokhtar</option>
              <option value='Sid Zouin'>Sid Zouin</option>
              <option value='Sidi Abdallah Ghiat'>Sidi Abdallah Ghiat</option>
              <option value='Sidi Addi'>Sidi Addi</option>
              <option value='Sidi Ahmed'>Sidi Ahmed</option>
              <option value='Sidi Ali Ban Hamdouche'>Sidi Ali Ban Hamdouche</option>
              <option value='Sidi Allal El Bahraoui'>Sidi Allal El Bahraoui</option>
              <option value='Sidi Allal Tazi'>Sidi Allal Tazi</option>
              <option value='Sidi Bennour'>Sidi Bennour</option>
              <option value='Sidi Bou Othmane'>Sidi Bou Othmane</option>
              <option value='Sidi Boubker'>Sidi Boubker</option>
              <option value='Sidi Bouknadel'>Sidi Bouknadel</option>
              <option value='Sidi Bouzid'>Sidi Bouzid</option>
              <option value='Sidi Ifni'>Sidi Ifni</option>
              <option value='Sidi Jaber'>Sidi Jaber</option>
              <option value='Sidi Kacem'>Sidi Kacem</option>
              <option value='Sidi Lyamani'>Sidi Lyamani</option>
              <option value='Sidi Mohamed ben Abdallah el-Raisuni'>Sidi Mohamed ben Abdallah el-Raisuni</option>
              <option value='Sidi Rahhal'>Sidi Rahhal</option>
              <option value='Sidi Rahhal Chataï'>Sidi Rahhal Chataï</option>
              <option value='Sidi Slimane'>Sidi Slimane</option>
              <option value='Sidi Slimane Echcharaa'>Sidi Slimane Echcharaa</option>
              <option value='Sidi Smaïl'>Sidi Smaïl</option>
              <option value='Sidi Taibi'>Sidi Taibi</option>
              <option value='Sidi Yahya El Gharb'>Sidi Yahya El Gharb</option>
              <option value='Skhinate'>Skhinate</option>
              <option value='Skhirate'>Skhirate</option>
              <option value='Skhour Rehamna'>Skhour Rehamna</option>
              <option value='Skoura'>Skoura</option>
              <option value='Smimou'>Smimou</option>
              <option value='Soualem'>Soualem</option>
              <option value='Souk El Arbaa'>Souk El Arbaa</option>
              <option value='Souk Sebt Oulad Nemma'>Souk Sebt Oulad Nemma</option>
              <option value='Stehat'>Stehat</option>
              <option value='Séfrou'>Séfrou</option>
              <option value='Tabounte'>Tabounte</option>
              <option value='Tafajight'>Tafajight</option>
              <option value='Tafetachte'>Tafetachte</option>
              <option value='Tafraout'>Tafraout</option>
              <option value='Taghjijt'>Taghjijt</option>
              <option value='Taghzout'>Taghzout</option>
              <option value='Tagzen'>Tagzen</option>
              <option value='Tahannaout'>Tahannaout</option>
              <option value='Tahla‎'>Tahla‎</option>
              <option value='Tala Tazegwaght‎'>Tala Tazegwaght‎</option>
              <option value='Taliouine'>Taliouine</option>
              <option value='Talmest'>Talmest</option>
              <option value='Talsint'>Talsint</option>
              <option value='Tamallalt'>Tamallalt</option>
              <option value='Tamanar'>Tamanar</option>
              <option value='Tamansourt'>Tamansourt</option>
              <option value='Tamassint‎'>Tamassint‎</option>
              <option value='Tamegroute'>Tamegroute</option>
              <option value='Tameslouht'>Tameslouht</option>
              <option value='Tamesna'>Tamesna</option>
              <option value='Tamraght'>Tamraght</option>
              <option value='Tan-Tan'>Tan-Tan</option>
              <option value='Tanalt'>Tanalt</option>
              <option value='Tanger‎'>Tanger‎</option>
              <option value='Tanoumrite Nkob Zagora'>Tanoumrite Nkob Zagora</option>
              <option value='Taounate‎'>Taounate‎</option>
              <option value='Taourirt'>Taourirt</option>
              <option value='Taourirt ait zaghar'>Taourirt ait zaghar</option>
              <option value='Tarfaya‎'>Tarfaya‎</option>
              <option value='Targuist‎'>Targuist‎</option>
              <option value='Taroudannt'>Taroudannt</option>
              <option value='Tata'>Tata</option>
              <option value='Taza‎'>Taza‎</option>
              <option value='Taïnaste‎'>Taïnaste‎</option>
              <option value='Temsia'>Temsia</option>
              <option value='Tendrara'>Tendrara</option>
              <option value='Thar Es-Souk‎'>Thar Es-Souk‎</option>
              <option value='Tichoute'>Tichoute</option>
              <option value='Tiddas'>Tiddas</option>
              <option value='Tiflet'>Tiflet</option>
              <option value='Tifnit'>Tifnit</option>
              <option value='Tighassaline'>Tighassaline</option>
              <option value='Tighza'>Tighza</option>
              <option value='Timahdite'>Timahdite</option>
              <option value='Tinejdad'>Tinejdad</option>
              <option value='Tisgdal'>Tisgdal</option>
              <option value='Tissa‎'>Tissa‎</option>
              <option value='Tit Mellil'>Tit Mellil</option>
              <option value='Tizguite'>Tizguite</option>
              <option value='Tizi Ouasli‎'>Tizi Ouasli‎</option>
              <option value='Tiznit'>Tiznit</option>
              <option value='Tiztoutine'>Tiztoutine</option>
              <option value='Touarga'>Touarga</option>
              <option value='Touima'>Touima</option>
              <option value='Touissit'>Touissit</option>
              <option value='Toulal'>Toulal</option>
              <option value='Toundoute'>Toundoute</option>
              <option value='Tounfite'>Tounfite</option>
              <option value='Témara'>Témara</option>
              <option value='Tétouan‎'>Tétouan‎</option>
              <option value='Youssoufia'>Youssoufia</option>
              <option value='Zag'>Zag</option>
              <option value='Zagora'>Zagora</option>
              <option value='Zaouia d'Ifrane'>Zaouia d'Ifrane</option>
              <option value='Zaouïat Cheikh'>Zaouïat Cheikh</option>
              <option value='Zaïda'>Zaïda</option>
              <option value='Zaïo'>Zaïo</option>
              <option value='Zeghanghane'>Zeghanghane</option>
              <option value='Zeubelemok'>Zeubelemok</option>
              <option value='Zinat'>Zinat</option>
            </select>